namespace FantaziaDesign.Interop
{

	public static partial class User32
	{
		public enum WCA
		{
			UNDEFINED,
			NCRENDERING_ENABLED,
			NCRENDERING_POLICY,
			TRANSITIONS_FORCEDISABLED,
			ALLOW_NCPAINT,
			CAPTION_BUTTON_BOUNDS,
			NONCLIENT_RTL_LAYOUT,
			FORCE_ICONIC_REPRESENTATION,
			EXTENDED_FRAME_BOUNDS,
			HAS_ICONIC_BITMAP,
			THEME_ATTRIBUTES,
			NCRENDERING_EXILED,
			NCADORNMENTINFO,
			EXCLUDED_FROM_LIVEPREVIEW,
			VIDEO_OVERLAY_ACTIVE,
			FORCE_ACTIVEWINDOW_APPEARANCE,
			DISALLOW_PEEK,
			CLOAK,
			CLOAKED,
			ACCENT_POLICY,
			FREEZE_REPRESENTATION,
			EVER_UNCLOAKED,
			VISUAL_OWNER,
			HOLOGRAPHIC,
			EXCLUDED_FROM_DDA,
			PASSIVEUPDATEMODE,
			USEDARKMODECOLORS,
			CORNER_STYLE,
			PART_COLOR,
			DISABLE_MOVESIZE_FEEDBACK,
			LAST
		}

	}
}
